"execute pathogen#infect() 
set history=1000
set nocompatible              " be iMproved, required
filetype on                   " required!
filetype plugin on
set autoread
set shortmess=atI
set pastetoggle=<F9>
" vim seems to recognize *.tex files as the plaintex fileype, not just tex
" so the tex.snippets file will not be enabled for them by default
let g:tex_flavor='latex'      
							  
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'

Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
" Plugin 'garbas/vim-snipmate'
" Track the engine.
Plugin 'SirVer/ultisnips'

" Plugin 'Valloric/YouCompleteMe'
" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" Trigger configuration:
"let g:UltiSnipsExpandTrigger="<tab>"
"let g:UltiSnipsJumpForwardTrigger="<c-b>"
"let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

call vundle#end()
"filetype plugin indent on    " required

" NERDTree
map <C-n> :NERDTreeToggle<CR>
"autocmd VimEnter * NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

syntax enable
syntax on
set tabstop=4
"set softtabstop=4
"set shiftwidth=4
set number
set hlsearch
set ignorecase
set incsearch

set nowrap
nnoremap <F2> : set nonumber!<CR>:set foldcolumn=0<CR>
" 状态行显示内容
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}:%{&fenc!=''?&fenc:&enc}]\ [TYPE=%Y]\ %r%h%=[POS=%l,%v][%p%%]\ [%{strftime(\"%Y/%m/%d\ %H:%M\")}]

" 状态行显示模式(0=不显示,1=两个窗口以上显示,2=始终显示)
set laststatus=2

" 命令行（在状态行下）的高度，默认为1，这里是2
set cmdheight=2

set showmatch
set mat=2

set foldenable
set foldmethod=marker

set ruler
set showcmd
set cursorline

" let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsExpandTrigger='<f9>'
let g:UltiSnipsListSnippets='<c-f9>'
let g:UltiSnipsJumpForwardTrigger='<f9>'
let g:UltiSnipsJumpBackwardTrigger='<s-f9>'

let g:ycm_global_ycm_extra_conf = "~/.ycm_extra_conf.py"

colo desert
set colorcolumn=80
